import { redirect } from "next/navigation";
import { RankingForm } from "@/components/RankingForm";
import { RankingResult } from "@/components/RankingResult";
import { auth } from "@/lib/auth";

export default async function DashboardPage() {
  const session = await auth();
  if (!session) {
    redirect("/");
  }

  return (
    <main className="mx-auto flex w-full max-w-5xl flex-col gap-8 px-6 py-12">
      <div className="space-y-2">
        <h1 className="text-3xl font-semibold text-gray-900">Ranking dashboard</h1>
        <p className="text-sm text-gray-600">
          Configure your evaluation criteria, submit candidates, and review the ordered list generated by OpenAI.
        </p>
      </div>
      <div className="grid gap-6 lg:grid-cols-2">
        <RankingForm />
        <RankingResult />
      </div>
    </main>
  );
}
