name: CI
on:
  push: { branches: ["**"] }
  pull_request: { branches: ["**"] }

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Print env (debug)
        run: |
          node -v
          npm -v
          npm config get registry
          npm config list -l | sed -n '1,80p' || true
          [ -f .npmrc ] && cat .npmrc || true

      - name: Harden npm
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-maxtimeout 120000
          npm config set audit false
          npm config set fund false

      - name: Install (verbose)
        run: npm ci --foreground-scripts --loglevel verbose

      - name: Prisma generate (best-effort)
        run: npx prisma generate || true

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build --silent

      - name: Print npm debug log on failure
        if: failure()
        run: |
          find ~/.npm/_logs -type f -name "*-debug-0.log" -print -exec tail -n +1 {} \;

      - name: Upload npm logs (artifact)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: ~/.npm/_logs/*-debug-0.log
          if-no-files-found: ignore
